# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from random_username.generate import generate_username
from random import seed
from random import randint
import keyboard

class TestCreateAccOldV2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.get('chrome://settings/clearBrowserData')
    time.sleep(10)
    keyboard.send("Enter")
    self.vars = {}
    
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_createAccOld(self):
    self.driver.get("https://old.reddit.com/login")
    self.driver.set_window_size(786, 824)
    self.driver.find_element(By.ID, "user_reg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".split-panel").click()
    username = generate_username(1)[0]+'-'+str(randint(100, 999))
    self.driver.find_element(By.ID, "user_reg").send_keys(username)
    self.driver.find_element(By.ID, "passwd_reg").click()
    self.driver.find_element(By.ID, "passwd_reg").send_keys(username+'1986')
    self.driver.find_element(By.ID, "passwd2_reg").click()
    self.driver.find_element(By.ID, "passwd2_reg").send_keys(username+'1986')
    print("waiting for 60s")
    time.sleep(120)
    self.driver.implicitly_wait(400)
    element = self.driver.find_element(By.LINK_TEXT, "preferences")   
    self.driver.get("https://old.reddit.com/prefs/apps/")
    time.sleep(5)
    #successful acc creation
    print(' '+'\n')
    print(username+'/'+username+'1986')
    with open("python.txt", "a") as myfile:
      myfile.write('\n'+username+'/'+username+'1986')
    self.driver.find_element(By.ID, "create-app-button").click()
    time.sleep(5)
    self.driver.find_element(By.NAME, "name").click()
    self.driver.find_element(By.NAME, "name").send_keys("app1")
    self.driver.find_element(By.ID, "app_type_script").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > .prefright").click()
    self.driver.find_element(By.NAME, "about_url").click()
    self.driver.find_element(By.NAME, "about_url").send_keys(generate_username(1)[0]+'-'+str(randint(1900, 4000))+".com")
    self.driver.find_element(By.NAME, "redirect_uri").send_keys("http://"+generate_username(1)[0]+'-'+str(randint(1900, 4000))+".com")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(6)").click()
    self.driver.find_element(By.CSS_SELECTOR, "h3:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, "h3:nth-child(3)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "h3:nth-child(3)")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "h3:nth-child(3)")
    assert len(elements) > 0
    var1 = self.driver.find_element(By.CSS_SELECTOR, "h3:nth-child(3)").text
    self.driver.find_element(By.CSS_SELECTOR, ".preftable:nth-child(4) tr:nth-child(1) > .prefright").click()
    self.driver.find_element(By.CSS_SELECTOR, ".preftable:nth-child(4) tr:nth-child(1) > .prefright").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".preftable:nth-child(4) tr:nth-child(1) > .prefright")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".preftable:nth-child(4) tr:nth-child(1) > .prefright")
    assert len(elements) > 0
    var2 = self.driver.find_element(By.CSS_SELECTOR, ".preftable:nth-child(4) tr:nth-child(1) > .prefright").text
    print('SUCCESS')
    print(username,' ',var1,' ',var2)
    with open("python.txt", "a") as myfile:
      myfile.write(' '+username+' '+var1+' '+var2)
    self.driver.find_element(By.ID, "header-bottom-right").click()
    self.driver.find_element(By.LINK_TEXT, "logout").click()
  
    def test_deleteApi(self):
      cars = ["soreWildfowl8-2748", "shamefulOryx6-2876"]
      for x in cars:
        print()
        self.driver.get("https://old.reddit.com/login")
        self.driver.set_window_size(786, 824)
        self.driver.find_element(By.ID, "user_reg").click()
        self.driver.find_element(By.CSS_SELECTOR, ".split-panel").click()
        username = x
        self.driver.find_element(By.ID, "user_login").click()
        self.driver.find_element(By.ID, "user_login").send_keys("shamefulOryx6-2876")
        self.driver.find_element(By.ID, "passwd_login").click()
        self.driver.find_element(By.ID, "passwd_login").send_keys("shamefulOryx6-28761986")
        self.driver.find_element(By.CSS_SELECTOR, ".c-clearfix:nth-child(7) > .c-btn").click()
        element = self.driver.find_element(By.LINK_TEXT, "Submit a new text post")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        print("waiting for 60s")
        time.sleep(10)
        self.driver.implicitly_wait(400)
        element = self.driver.find_element(By.LINK_TEXT, "preferences")   
        self.driver.get("https://old.reddit.com/prefs/apps/")
        time.sleep(5)
        #successful acc creation
        print(' '+'\n')
        print(username+'/'+username+'1986')
        self.driver.find_element(By.LINK_TEXT, "edit").click()
        self.driver.find_element(By.LINK_TEXT, "delete app").click()
        self.driver.find_element(By.LINK_TEXT, "yes").click()
        self.driver.find_element(By.ID, "create-app-button").click()
        time.sleep(5)
        self.driver.find_element(By.NAME, "name").click()
        self.driver.find_element(By.NAME, "name").send_keys("app1")
        self.driver.find_element(By.ID, "app_type_script").click()
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > .prefright").click()
        self.driver.find_element(By.NAME, "about_url").click()
        self.driver.find_element(By.NAME, "about_url").send_keys(generate_username(1)[0]+'-'+str(randint(1900, 4000))+".com")
        self.driver.find_element(By.NAME, "redirect_uri").send_keys("http://"+generate_username(1)[0]+'-'+str(randint(1900, 4000))+".com")
        self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(6)").click()
        self.driver.find_element(By.CSS_SELECTOR, "h3:nth-child(3)").click()
        self.driver.find_element(By.CSS_SELECTOR, "h3:nth-child(3)").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "h3:nth-child(3)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        elements = self.driver.find_elements(By.CSS_SELECTOR, "h3:nth-child(3)")
        assert len(elements) > 0
        var1 = self.driver.find_element(By.CSS_SELECTOR, "h3:nth-child(3)").text
        self.driver.find_element(By.CSS_SELECTOR, ".preftable:nth-child(4) tr:nth-child(1) > .prefright").click()
        self.driver.find_element(By.CSS_SELECTOR, ".preftable:nth-child(4) tr:nth-child(1) > .prefright").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".preftable:nth-child(4) tr:nth-child(1) > .prefright")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        elements = self.driver.find_elements(By.CSS_SELECTOR, ".preftable:nth-child(4) tr:nth-child(1) > .prefright")
        assert len(elements) > 0
        var2 = self.driver.find_element(By.CSS_SELECTOR, ".preftable:nth-child(4) tr:nth-child(1) > .prefright").text
        print('SUCCESS')
        print(username,' ',var1,' ',var2)
        with open("python.txt", "a") as myfile:
          myfile.write('\n'+username+'/'+username+'1986')
          myfile.write(' '+username+' '+var1+' '+var2)
        self.driver.find_element(By.ID, "header-bottom-right").click()
        self.driver.find_element(By.LINK_TEXT, "logout").click()
